name: Parameterized Build Workflow

on:
  workflow_dispatch:
    inputs:
      parameter_one:
        description: 'Parameter One'
        required: true
      parameter_two:
        description: 'Parameter Two'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PARAMETER_ONE: ${{ github.event.inputs.parameter_one }}
      PARAMETER_TWO: ${{ github.event.inputs.parameter_two }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building with PARAMETER_ONE=${PARAMETER_ONE} and PARAMETER_TWO=${PARAMETER_TWO}"
          # Your build steps here
