name: Parameterized Build Workflow

on:
  workflow_dispatch:
    inputs:
      parameter_choice:
        description: 'Choose a parameter (OptionA, OptionB, OptionC, or OptionD)'
        required: true
        #default: 'OptionA'  # Default value in case the user doesn't provide one

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write 
      issues: read
      packages: none
  
    env:
      PARAMETER_CHOICE: ${{ github.event.inputs.parameter_choice }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone other repository
        uses: actions/checkout@v3
        with:
          repository: 'noaman-bacancy/testsa.git'
          path: 'testsa'
          token: ${{ github.token }}
          
      # - name: test
      #   run: git clone https://noaman-bacancy:${{ secrets.GITHUB_TOKEN }}@github.com/noaman-bacancy/testsa.git
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
        
      - name: Validate Parameter
        run: |
          valid_options=("OptionA" "OptionB" "OptionC" "OptionD")
          if [[ ! " ${valid_options[@]} " =~ " ${PARAMETER_CHOICE} " ]]; then
            echo "Invalid option. Please choose from: ${valid_options[@]}"
            exit 1
          fi

      - name: Build
        run: |
          echo "Building with PARAMETER_CHOICE=${PARAMETER_CHOICE}"
          # Your build steps here
