name: Parameterized Build Workflow

on:
  workflow_dispatch:
    inputs:
      parameter_choice:
        description: 'Choose a parameter (OptionA, OptionB, OptionC, or OptionD)'
        required: true
        #default: 'OptionA'  # Default value in case the user doesn't provide one

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write 
      issues: read
      packages: none
  
    env:
      PARAMETER_CHOICE: ${{ github.event.inputs.parameter_choice }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: test
        run: gh repo clone noaman-bacancy/time_tracker
        
      - name: Validate Parameter
        run: |
          valid_options=("OptionA" "OptionB" "OptionC" "OptionD")
          if [[ ! " ${valid_options[@]} " =~ " ${PARAMETER_CHOICE} " ]]; then
            echo "Invalid option. Please choose from: ${valid_options[@]}"
            exit 1
          fi

      - name: Build
        run: |
          echo "Building with PARAMETER_CHOICE=${PARAMETER_CHOICE}"
          # Your build steps here
