name: test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Determine Changed Tools
      id: changed_tools
      run: |
        echo "{name}={value}" >> $GITHUB_STATE
        echo "{name}={value}" >> $GITHUB_OUTPUT

        echo $GITHUB_STATE
        echo $GITHUB_OUTPUT
